@host = localhost
@port = 8000
@hostname = http://{{host}}:{{port}}
@route = /api/v1/contacts
@paramsId = {{postContact.response.body.data.$._id}}
@querySelect = select=name.firstName
@querySort = sort=name
@querylimit = limit=6
@querypage = page=10

### 
# @name getAllContacts
GET {{hostname}}{{route}}


### 
# @name getContactById
GET {{hostname}}{{route}}/{{paramsId}}


###
# @name postContact
POST {{hostname}}{{route}}
Content-Type: application/json

{
   "salutation": "Mdm",
  "name": {
    "firstName": "Charmander",
    "lastName": "Fire",
    "alias": "碧萱"
  },
  "organisation": "Pokemon Center",
  "position": "Fusce posuere felis sed lacus.",
  "address": "1 HarbourFront Walk Singapore",
  "activateGeocode": true,
  "contact": {
    "telephone": "+7-812-937-8305",
    "mobile": "6559256698",
    "email": "gbellsham0@hud.gov"
  },
  "notes": "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros."
}



###
PUT {{hostname}}{{route}}/{{paramsId}}
Content-Type: application/json

{
 "name": {
    "firstName": "Blue",
    "lastName": "Berry"
  },
  "salutation": "Ms",
  "address": "140 bedok reservoir road",
  "addressTouched": true,
  "activateGeocode": true
}


###
DELETE  {{hostname}}{{route}}/{{paramsId}}
